### ISSUE TITLE
Only local variables and function's arguments are displayed for now

### ISSUE THREAD

**Issue by AlexTrotsenko** [AlexTrotsenko/j2v8-debugger#1]
Reason:  variables are obtained from current V8 Frame.

Check if we can get info about global variables. Check, other data source like [scopes](https://github.com/AlexTrotsenko/j2v8-debugger/commit/fc2987da6b089e0eff572f83b9bcfde16a05b93b#diff-612bd827bb351732cec88fe0e0644369L361), etc.

**Comment by jamie-houston** [comment]
This is fixed with https://github.com/AlexTrotsenko/j2v8-debugger/pull/7.  Global variables are available with inspection api.
