### ISSUE TITLE
Use latest chrome, CDT cannot be opened correctly.

### ISSUE THREAD

**Issue by yinyinnie** [AlexTrotsenko/j2v8-debugger#16]
pls reference this issue: https://github.com/facebook/stetho/issues/696

**Comment by AlexTrotsenko** [comment]
@yinyinnie  do you mean adding mentioning of this issue in the readme or ? 
I don't see any fix nor work-around beside using the old version of Chrome, etc.

**Comment by yinyinnie** [comment]
I mean that this problem is caused by https://github.com/facebook/stetho/issues/696.

**Comment by yinyinnie** [comment]
And I have a question: if we want to fix this issue,  should we modify the code of facebook/stetho?

**Comment by AlexTrotsenko** [comment]
@yinyinnie  I believe that doing changes on the `facebook/stetho` side could be a good idea - if you have a capacity - feel free to proceed with it.
Alternatively, as mentioned in that issue description, using the old Chrome version could be a work-around to run `j2v8-debugger` with `stetho`.

**Comment by yinyinnie** [comment]
i have fix  this issue, pls help merge this PR #18
