### ISSUE TITLE
All keys of V8 objects are displayed twice.

### ISSUE THREAD

**Issue by AlexTrotsenko** [AlexTrotsenko/j2v8-debugger#3]
Reason: Chrome DevTools UI calls Runtime.getProperties() twice for unknown reason.

todo: figure-out why this happens and how to avoid this if possible to have nice variables inspection UI.

**Comment by jamie-houston** [comment]
This is fixed with https://github.com/AlexTrotsenko/j2v8-debugger/pull/7

**Comment by AlexTrotsenko** [comment]
fixed in https://github.com/AlexTrotsenko/j2v8-debugger/pull/7
