### ISSUE TITLE
StethoHelper.notifyScriptsChanged() currently closes Chrome DevTools connection.

### ISSUE THREAD

**Issue by AlexTrotsenko** [AlexTrotsenko/j2v8-debugger#4]
Instead it should update script source code in Chrome DevTools.

Reason: No simple "script changed" event was found in Chrome DevTools protocol.

Currently as work-around, when Chrome DevTools is re-opened - it will show new version of JS scripts.

**Comment by jamie-houston** [comment]
This is fixed with https://github.com/AlexTrotsenko/j2v8-debugger/pull/7
