### ISSUE TITLE
Evaluation of random JS expression is not working

### ISSUE THREAD

**Issue by AlexTrotsenko** [AlexTrotsenko/j2v8-debugger#5]
It would be nice for debugging to be able to evaluate new JS expression when debugger is paused.
_(not implemented yet.)_

**Comment by jamie-houston** [comment]
This is fixed with https://github.com/AlexTrotsenko/j2v8-debugger/pull/7

**Comment by AlexTrotsenko** [comment]
fixed in https://github.com/AlexTrotsenko/j2v8-debugger/pull/7
