### ISSUE TITLE
Not working with latest v8 builds

### ISSUE THREAD

**Issue by jhorst11** [AlexTrotsenko/j2v8-debugger#6]
V8 dropped the debug api that DebugHandler relies on so the debugger no longer works on later builds of v8. j2v8 will need to support the inspector api to re-enable debugging and j2v8-debugger will need to interface with that instead of the current DebugHandler.

There’s an open PR on j2v8 to add support for the inspector api: https://github.com/eclipsesource/J2V8/pull/491

**Comment by AlexTrotsenko** [comment]
@jhorst11  thanks for reporting an issue. 

Changes are already implemented by  @jamie-houston. 

I have released `0.2.0`, it's available in JitPack already:
https://jitpack.io/#AlexTrotsenko/j2v8-debugger/0.2.0

**Comment by jhorst11** [comment]
thanks @AlexTrotsenko & @jamie-houston !
